language: java
dist: bionic
sudo: false
jdk:
  - openjdk11
script:
  # validate scripts
  - shellcheck *.sh

  # dry run of all the scripts
  - ./setup-validator.sh
  - ./validate.sh "https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore-expanded.yaml"
